name: discover_printers
description: A new Flutter project.

version: 1.0.0+1
publish_to: none
environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  charset_converter: ^2.1.1
  cupertino_icons: ^1.0.6
  esc_pos_printer:
    path: ../../
  esc_pos_utils:
    git:
      url: https://github.com/srengty/esc_pos_utils.git
      ref: master
  flutter:
    sdk: flutter
  image: ^4.1.3
  intl: ^0.18.1
  path_provider: ^2.1.1
  ping_discover_network_forked: ^0.0.1
  qr_flutter: ^4.1.0
  network_info_plus: ^6.1.3
  # wifi:
  #   git:
  #     url: https://github.com/srengty/wifi.git
  #     ref: master
  # esc_pos_utils:
  # path: ../../../esc_pos_utils

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/rabbit_black.jpg
