name: esc_pos_printer
description: The library allows to print receipts using an ESC/POS thermal WiFi printer.
version: 4.1.0
homepage: https://github.com/andrey-ushakov/esc_pos_printer

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  charset_converter: ^2.3.0
  esc_pos_utils:
    git:
      url: https://github.com/srengty/esc_pos_utils.git
      ref: master
  flutter:
    sdk: flutter
  # esc_pos_utils:
  #   path: ../esc_pos_utils
  image: ^4.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
